# config.yml
"002":
  - class002_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=22.09.2014:20:00:00
"003":
  - class003_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=24.09.2014:20:00:00
"004":
  - class004
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=29.09.2014:20:00:00
"009":
  - class009_homework
  - type_reports
  - git log --after=15.09.2014:11:10:00 --until=27.10.2014:20:00:00
"012":
  - class012_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=10.11.2014:20:00:00
"014":
  - class014_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=13.11.2014:06:00:00
"015":
  - class015_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=20.11.2014:06:00:00
"017-1":
  - class017_homework/homework1
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=02.12.2014:06:00:00
"017-2":
  - class017_homework/homework2
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=02.12.2014:06:00:00
"018":
  - class018_homework
  - type_programs
  - git log --after=15.09.2014:11:10:00 --until=04.12.2014:06:00:00
"VH":
  - vhodno_nivo
  - type_3_programs
  - git log --after=15.09.2014:11:10:00 --until=17.09.2014:20:00:00	
