'VH':
 - 'vhodno_nivo/**/*_*_*.*'
 -  17.09.2014:20:00:00
'009':
 -  'class009_homework/**/*.pdf'
 -  27.10.2014:20:00:00
 -  'class009_homework/project_to_names.csv'
'002':
 - 'class002_homework/**/*_*_*_*.rb'
 -  22.09.2014:20:00:00
'003':
 -  'class003_homework/**/*_*_*_*.rb'
 -  24.09.2014:20:00:00
'004':
 - 'class003_homework/**/*_*_*_*.rb'
 - 24.09.2014:20:00:00
'004':
 -  'class004/*_*_*_*.rb'
 -  29.09.2014:20:00:00
'012':
 -  'class012_homework/**/*_*_*_*.rb'
 -  10.11.2014:20:00:00
'014':
 -  'class014_homework/**/*_*_*_*.rb'
 -  13.11.2014:06:00:00
'0171':
 -  'class017_homework/homework1/**/*_*_*_*.rb'
 -  02.12.2014:06:00:00
'0172':
 -  'class017_homework/homework2/**/*_*_*_*.rb'
 -  02.12.2014:06:00:00
'mainRow':
- 'VH'
- '002'
- '003'
- '004'
- '009'
- '012'
- '014'
- '0171'
- '0172'
- 'g2'
- 'g3'
- 'g4'
- 'g9'
- 'g12'
- 'g14'
- 'g171'
- 'g172'
- 'y2'
- 'y3'
- 'y4'
- 'y9'
- 'y12'
- 'y14'
- 'y171'
- 'y172'
'directory':
- 'vhodno_nivo'
- 'class002_homework'
- 'class003_homework'
- 'class004'
- 'class009_homework'
- 'class012_homework'
- 'class014_homework'
- 'class017_homework'