"homeworks":
 'VH':
 - vhodno_nivo/**/*_*_*.*
 - --until=17.09.2014:20:00
 '002':
 - class002_homework/**/*_*_*_*.rb
 - --until=22.09.2014:20:00
 '003':
 - class003_homework/**/*_*_*_*.rb
 - --until=24.09.2014:20:00
 '004':
 - class004/**/*_*_*_*.rb
 - --until=29.09.2014:20:00
 '009':
 - class009_homework/**/*.pdf
 - --until=27.10.2014:20:00
 '012':
 - class012_homework/**/*_*_*_*.rb
 - --until=10.11.2014:20:00
 '014':
 - class014_homework/**/*_*_*_*.rb
 - --until=13.11.2014:06:00
 '015':
 - class015_homework/**/*_*_*_*.rb
 - --until=20.11.2014:06:00
 '017-1':
 - class017_homework/homework1/*_*_*_*.rb
 - --until=02.12.2014:06:00
 '017-2':
 - class017_homework/homework2/*
 - --until=02.12.2014:06:00
 '018':
 - class018_homework/*
 - --until=04.12.2014:06:00

"init_student":
 'VH': 0
 '002': 0
 '003': 0
 '004': 0
 '009': 0
 '012': 0
 '014': 0
 '015': 0
 '017-1': 0
 '017-2': 0
 '018': 0
 'g2' : '-'
 'g3' : '-'
 'g4' : '-'
 'g12' : '-'
 'g14' : '-'
 'g15' : '-'
 'g17-1' : '-'
 'g17-2' : '-'
 'g18' : '-'
 'y2' : '-'
 'y3' : '-'
 'y4' : '-'
 'y12' : '-'
 'y14' : '-'
 'y15' : '-'
 'y17-1' : '-'
 'y17-2' : '-'
 'y18' : '-'
