homeworks:
 'vhodno_nivo': vhodno_nivo/**/*_*_*.*
 '002': class002_homework/*_*_*_*.rb
 '003': class003_homework/*_*_*_*.rb
 '004': class004/*_*_*_*.rb
 '009': class009_homework/
 '012': class012_homework/*_*_*_*.rb
 '014': class014_homework/**/*_*_*_*.rb
 '015': class015_homework/**/*_*_*_*.rb
 '017-1': class017_homework/homework1/*_*_*_*.rb
 '017-2': class017_homework/homework2/**/*_*_*_*.rb
 '018': class018_homework/**/*_*_*_*.rb
 
deadlines:
 'vhodno_nivo':  Sep--17--2014--20:00:00
 '002': Sep--22--2014--20:00:00
 '003': Sep--24--2014--20:00:00
 '004': Sep--29--2014--20:00:00
 '009': Oct--27--2014--20:00:00
 '012': Nov--10--2014--20:00:00
 '014': Nov--13--2014--06:00:00
 '015': Nov--20--2014--06:00:00
 '017-1': Dec--2--2014--06:00:00
 '017-2': Dec--2--2014--06:00:00
 '018': Dec--4--2014--06:00:00

flog:
 '002': g2
 '003': g3
 '004': g4
 '012': g12
 '014': g14
 '015': g15
 '017-1': g17-1
 '017-2': g17-2
 '018': g18
 
flay:
 '002': y2
 '003': y3
 '004': y4
 '012': y12
 '014': y14
 '015': y15
 '017-1': y17-1
 '017-2': y17-2
 '018': y18

filename: results_Valentin_Varbanov_B_4
